### PR TITLE
Fix #34 Make `devdocs-install` exclude already installed docs

### LINKED ISSUE #34: [feature request] Make `devdocs-install` exclude already installed docs.

### PR DESCRIPTION
**Pull request by stardiviner**
Fix #34

### CODE REVIEW

**Comment by astoff** [comment]
With this change, you can't reinstall / update a installed document...

I think I understand where you want to get with this, see if https://github.com/astoff/devdocs.el/issues/29#issuecomment-1828150320 is relevant. I don't see an easy fix for the problem, though.

**Comment by stardiviner** [comment]
I don't think so, the word `install` means doc is not installed, if user want to update doc, then should call command like `devdocs-update`. WDYT? If a package manager use `install` to upgrade package, I think any user will be confused.

**Comment by stardiviner** [comment]
Hi, any update on this PR? I don't think https://github.com/astoff/devdocs.el/issues/29#issuecomment-1828150320 is very same with this PR purpose.

**Comment by astoff** [comment]
As mentioned above, this change would make it impossible to reinstall an already installed document.

**Pull request closed without merging**
